[package]
name = "rust"
version = "0.1.0"
authors = ["Paul <spaynkee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "18.2.0"
actix-web = "2.0.0"
actix-files = "0.2.2"
actix-rt = "1.0.0"
env_logger = "0.7"
rustc-serialize = "0.3"
config = "0.10.1"
serde_qs = "0.6.1"
serde_derive = "1.0.115"
serde = "1.0.115"
futures = "0.3"
serde_json = "1.0.105"
log = "0.4"
futures-util = "0.3"
bytes = "1.5"
opencv = { version = "0.91", features = ["buildtime-bindgen"] }

[dependencies.mongodb]
version = "2.6.1"
features = ["tokio-sync"]
default-features = false
