# Generated by Django 5.2.5 on 2025-08-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lolData", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamdata",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
