# Generated by Django 5.2.5 on 2025-08-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lolData", "0002_alter_teamdata_duration"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LeagueUsers",
            new_name="LeagueUser",
        ),
        migrations.AddField(
            model_name="leagueuser",
            name="summoner_group",
            field=models.IntegerField(default=1),
        ),
        migrations.RenameModel(
            old_name="Champions",
            new_name="Champion",
        ),
        migrations.AddField(
            model_name="teamdata",
            name="summoner_group",
            field=models.IntegerField(default=1),
        ),
    ]
